<div class="a-section celwidget" id="customer_review-R17Z83IAQ6Y4VV"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AFS2REOLXQPOIJ4HO7OHH3NMWQNA/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/d83d1055-01ad-4b1f-838d-b2f827af7b9b._CR0,0,382,382_SX48_.jpg" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/d83d1055-01ad-4b1f-838d-b2f827af7b9b._CR0,0,382,382_SX48_.jpg"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">Les Scott</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/R17Z83IAQ6Y4VV/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="5.0 out of 5 stars"><i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R17Z83IAQ6Y4VV/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>The sizing is generous, quality seems good.</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on December 18, 2019</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  Great bag for storage. I'm planning on using it for a flight to Mexico. I've never used one before, so I don't know how it will go. I'm going to wrap my board with a moving blanket wrapped around it inside the bag.<br/>I have an epoxy board, so I think it will hold up fine.<br/>My main reason for my review is to talk about the size. I ordered the 9'2" for my 9'2" board. I'm glad I did. I have almost 6" to spare. I measured my board and it IS 9'2".<br/>The width will be tight after wrapping with the blanket, but that may be a good thing. I'll try to remember to update after my trip.<br/>Check the pictures.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-popover-preload" id="a-popover-R17Z83IAQ6Y4VV_gallerySection_main">
<div class="a-section cr-lightbox-popover-container" data-hook="image-popover" id="R17Z83IAQ6Y4VV_image_popover">
<div class="cr-lightbox-image-viewer">
<div class="cr-lightbox-main-image-container">
<img alt="Customer image" class="cr-lightbox-main-image" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/transparent-pixel._V192234675_.gif"/>
</div>
<div class="cr-lightbox-navigator-container cr-lightbox-navigator-container__back">
<div class="cr-lightbox-navigator-button cr-lightbox-navigator-button__back">
</div>
</div>
<div class="cr-lightbox-navigator-container cr-lightbox-navigator-container__next">
<div class="cr-lightbox-navigator-button cr-lightbox-navigator-button__next">
</div>
</div>
</div>
<div class="a-section cr-lightbox-review-information">
<div class="a-section a-spacing-mini">
<i class="a-icon a-icon-star a-star-5"><span class="a-icon-alt">5.0 out of 5 stars</span></i>
<span class="a-size-base a-text-bold">
                The sizing is generous, quality seems good.
            </span>
<br/>
<span class="a-size-small a-color-secondary">
            
              
                  By Les Scott on December 18, 2019
              
              
            


            </span>
</div>
<span class="a-size-base">
            Great bag for storage. I'm planning on using it for a flight to Mexico. I've never used one before, so I don't know how it will go. I'm going to wrap my board with a moving blanket wrapped around it inside the bag.<br/>I have an epoxy board, so I think it will hold up fine.<br/>My main reason for my review is to talk about the size. I ordered the 9'2" for my 9'2" board. I'm glad I did. I have almost 6" to spare. I measured my board and it IS 9'2".<br/>The width will be tight after wrapping with the blanket, but that may be a good thing. I'll try to remember to update after my trip.<br/>Check the pictures.
        </span>
<div class="a-section a-spacing-top-base">
<span class="a-size-medium a-color-secondary">
                Images in this review
            </span>
<div class="a-section a-spacing-top-mini cr-lightbox-image-thumbnails">
<img alt="Customer image" class="cr-lightbox-image-thumbnail" src="https://images-na.ssl-images-amazon.com/images/I/616gU5a5vVL._SY88.jpg"/>
<img alt="Customer image" class="cr-lightbox-image-thumbnail" src="https://images-na.ssl-images-amazon.com/images/I/71Ggh79HVLL._SY88.jpg"/>
<img alt="Customer image" class="cr-lightbox-image-thumbnail" src="https://images-na.ssl-images-amazon.com/images/I/71JjlCIu1FL._SY88.jpg"/>
<img alt="Customer image" class="cr-lightbox-image-thumbnail" src="https://images-na.ssl-images-amazon.com/images/I/71giEysnVRL._SY88.jpg"/>
</div>
</div>
</div>
</div>
</div><div class="a-section a-spacing-medium review-image-container" id="R17Z83IAQ6Y4VV_imageSection_main"><div class="review-image-tile-section" data-reviewid="R17Z83IAQ6Y4VV">
<span class="a-declarative" data-a-modal='{"name":"R17Z83IAQ6Y4VV_gallerySection_main"}' data-action="a-modal" id="R17Z83IAQ6Y4VV-0"><a class="a-popover-trigger a-declarative" href="javascript:void(0)"><img alt="Customer image" class="review-image-tile a-lazy-loaded" data-hook="review-image-tile" data-src="https://images-na.ssl-images-amazon.com/images/I/616gU5a5vVL._SY88.jpg" height="88" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif" width="100%"/><noscript><img alt="Customer image" height="88" src="https://images-na.ssl-images-amazon.com/images/I/616gU5a5vVL._SY88.jpg" width="100%"/></noscript><i class="a-icon a-icon-popover"></i></a></span><span class="a-declarative" data-a-modal='{"name":"R17Z83IAQ6Y4VV_gallerySection_main"}' data-action="a-modal" id="R17Z83IAQ6Y4VV-1"><a class="a-popover-trigger a-declarative" href="javascript:void(0)"><img alt="Customer image" class="review-image-tile a-lazy-loaded" data-hook="review-image-tile" data-src="https://images-na.ssl-images-amazon.com/images/I/71Ggh79HVLL._SY88.jpg" height="88" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif" width="100%"/><noscript><img alt="Customer image" height="88" src="https://images-na.ssl-images-amazon.com/images/I/71Ggh79HVLL._SY88.jpg" width="100%"/></noscript><i class="a-icon a-icon-popover"></i></a></span><span class="a-declarative" data-a-modal='{"name":"R17Z83IAQ6Y4VV_gallerySection_main"}' data-action="a-modal" id="R17Z83IAQ6Y4VV-2"><a class="a-popover-trigger a-declarative" href="javascript:void(0)"><img alt="Customer image" class="review-image-tile a-lazy-loaded" data-hook="review-image-tile" data-src="https://images-na.ssl-images-amazon.com/images/I/71JjlCIu1FL._SY88.jpg" height="88" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif" width="100%"/><noscript><img alt="Customer image" height="88" src="https://images-na.ssl-images-amazon.com/images/I/71JjlCIu1FL._SY88.jpg" width="100%"/></noscript><i class="a-icon a-icon-popover"></i></a></span><span class="a-declarative" data-a-modal='{"name":"R17Z83IAQ6Y4VV_gallerySection_main"}' data-action="a-modal" id="R17Z83IAQ6Y4VV-3"><a class="a-popover-trigger a-declarative" href="javascript:void(0)"><img alt="Customer image" class="review-image-tile a-lazy-loaded" data-hook="review-image-tile" data-src="https://images-na.ssl-images-amazon.com/images/I/71giEysnVRL._SY88.jpg" height="88" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif" width="100%"/><noscript><img alt="Customer image" height="88" src="https://images-na.ssl-images-amazon.com/images/I/71giEysnVRL._SY88.jpg" width="100%"/></noscript><i class="a-icon a-icon-popover"></i></a></span></div>
</div><script>
        P.when('A', 'cr-image-popover-controller').execute(function(A, imagePopoverController) {
          A.on("a:popover:beforeShow:R17Z83IAQ6Y4VV_gallerySection_main", function(data) {
            imagePopoverController.initImagePopover("R17Z83IAQ6Y4VV", "[https://images-na.ssl-images-amazon.com/images/I/616gU5a5vVL.jpg, https://images-na.ssl-images-amazon.com/images/I/71Ggh79HVLL.jpg, https://images-na.ssl-images-amazon.com/images/I/71JjlCIu1FL.jpg, https://images-na.ssl-images-amazon.com/images/I/71giEysnVRL.jpg]", data);
          });
        });
    </script>
<div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">7 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DR17Z83IAQ6Y4VV%26voteValue%3D1%26csrfT%3DgkA13PhH6QZIHPvKY1bFIfvrxa9mr0VrRoFejHMAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23R17Z83IAQ6Y4VV&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gkA13PhH6QZIHPvKY1bFIfvrxa9mr0VrRoFejHMAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R17Z83IAQ6Y4VV&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gkA13PhH6QZIHPvKY1bFIfvrxa9mr0VrRoFejHMAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R17Z83IAQ6Y4VV&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-R916RKVVV1L11"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AEKPKRN67766L6U6AUUATWUDLNQQ/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">VanessaM</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/R916RKVVV1L11/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="4.0 out of 5 stars"><i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R916RKVVV1L11/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Good enough!</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on February 13, 2019</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-color-secondary" data-hook="format-strip-linkless">Size: 9'6</span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  Overall this is a good day bag. Materials seem to be of decent quality. The zipper pulls are heavy duty plastic and will hopefully hold up for the long term. The only reason for docking 1 star is because the padding is a bit thinner than 2 other day bags I own (got them years ago for $50 which is a steal by today's pricing). I have a particularly heavy glassed old school longboard and I would feel more confident in this bag if it had a tad more padding. I'd still recommend this bag for those in search of a bag that's strictly for protection against the inevitable dings and dents that we all dread.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">7 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DR916RKVVV1L11%26voteValue%3D1%26csrfT%3DgrM0wI1dE%252B0w5laq8egp6ZFCr1hREjoX7Pj2L%252FYAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23R916RKVVV1L11&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=grM0wI1dE%2B0w5laq8egp6ZFCr1hREjoX7Pj2L%2FYAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R916RKVVV1L11&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=grM0wI1dE%2B0w5laq8egp6ZFCr1hREjoX7Pj2L%2FYAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R916RKVVV1L11&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-R10IUN6WXDLNTN"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AEZLFIRYOINECNNAY5O5R7E6FYZQ/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">Sarah Thom</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/R10IUN6WXDLNTN/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="1.0 out of 5 stars"><i class="a-icon a-icon-star a-star-1 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">1.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R10IUN6WXDLNTN/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Do not get this bag unless your only using it to transport a DRY surfboard in airport....</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on April 23, 2020</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  For the sport of surfing, this bag is HORRIBLE.  It leaks water everywhere.  I emailed the company who said, "well its not water resistant".  I find it strange to make a bag for surfing that doesn't work well with water.  If the board is wet at all, it sticks to the bag making it hard to take in and out.  Water seems to enter from the outside of the bag (if its raining and your using it for roof racks) then it pours out when you take the bag off the car.  Just spend the extra money and get a real surfboard bag if your a surfer!  Totally not worth the cheap price.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">4 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DR10IUN6WXDLNTN%26voteValue%3D1%26csrfT%3DgidxfGrs6u86AGDwUQEV%252BqbLMJ1mK%252BClNxFoRBoAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23R10IUN6WXDLNTN&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gidxfGrs6u86AGDwUQEV%2BqbLMJ1mK%2BClNxFoRBoAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R10IUN6WXDLNTN&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gidxfGrs6u86AGDwUQEV%2BqbLMJ1mK%2BClNxFoRBoAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R10IUN6WXDLNTN&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-R3A89I9SE3XAAU"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AFP4YZHXYZAXSCGU5E7DRNOCMHKQ/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">Mich</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/R3A89I9SE3XAAU/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="4.0 out of 5 stars"><i class="a-icon a-icon-star a-star-4 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">4.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R3A89I9SE3XAAU/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Well this bag is pretty much made of the same material</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on June 3, 2018</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-color-secondary" data-hook="format-strip-linkless">Size: 8’8</span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  Just go the bag today. Quick shipping. Have you ever seen one of those thick silver tarps they use to cover stuff with? Well this bag is pretty much made of the same material. Even smells like it, yeah its kinda got that chemical/plastic smell thing going for it, lol. I wouldn't leave it outside for long periods of time as it will probably degrade pretty quickly. Otherwise the product looks great! The zipper looks of high quality, the stitching is good. This is a great bag for the money, if you want something of higher quality, you will need to fork out double what this bag costs.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">3 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DR3A89I9SE3XAAU%26voteValue%3D1%26csrfT%3DglruH%252BhI0yYxmvAsW9n8f%252BfzGJXKTj1CCc%252BApawAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23R3A89I9SE3XAAU&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=glruH%2BhI0yYxmvAsW9n8f%2BfzGJXKTj1CCc%2BApawAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R3A89I9SE3XAAU&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=glruH%2BhI0yYxmvAsW9n8f%2BfzGJXKTj1CCc%2BApawAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R3A89I9SE3XAAU&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-RBTFMGYQ60GG7"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AHAUIHHKCQITLAI5OZW33TR6SYWA/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/8b7ff3f1-9812-42f1-8429-a3246bc74cfb._CR93,0,313,313_SX48_.jpg" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/8b7ff3f1-9812-42f1-8429-a3246bc74cfb._CR93,0,313,313_SX48_.jpg"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">Adam</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/RBTFMGYQ60GG7/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="5.0 out of 5 stars"><i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/RBTFMGYQ60GG7/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Glad I bought it</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on June 7, 2019</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-color-secondary" data-hook="format-strip-linkless">Size: 7'6</span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  This is a really good deal for the price. I have a 7'6 board and it fits in the 7'6 bag while leaving a few inches of space. I'm happy as it was about half the price of bags I was seeing in the surf shops. It definitely is right for my needs which was just storage and travel to the beach so my board would be protected in the car. The only negative is that it is slightly more thin than other bags I've owned but not enough to where it bothers me I feel like the padding is adequate.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">3 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DRBTFMGYQ60GG7%26voteValue%3D1%26csrfT%3Dgh9Hc5nImn1a%252FI%252Bo2CGN%252FeXpKE50q4IrjvQ0IpYAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23RBTFMGYQ60GG7&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gh9Hc5nImn1a%2FI%2Bo2CGN%2FeXpKE50q4IrjvQ0IpYAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=RBTFMGYQ60GG7&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gh9Hc5nImn1a%2FI%2Bo2CGN%2FeXpKE50q4IrjvQ0IpYAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=RBTFMGYQ60GG7&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-R3IMG32674IFV4"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AGNQPPTKVN7GAXQ4LNE4NG3V4DOQ/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/b1126910-fbb4-4b44-abdf-bb6e9387557a._CR0,0,500,500_SX48_.jpg" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/b1126910-fbb4-4b44-abdf-bb6e9387557a._CR0,0,500,500_SX48_.jpg"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">GNUU</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/R3IMG32674IFV4/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="5.0 out of 5 stars"><i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R3IMG32674IFV4/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Very pleased!</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on July 14, 2019</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-color-secondary" data-hook="format-strip-linkless">Size: 8’8</span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  Really didn’t know what to expect. Pricing vs. competitors vs. quality... upon opening up the package It wasn’t hard to feel and see the quality. I am beyond happy with this purchase. Great for day use. Enough padding for those bumps along the way. My board is 8’6” and it for fine. My only wish is that I could tuck the shoulder strap within the bag. I found a way to tuck strap within handle.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">2 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DR3IMG32674IFV4%26voteValue%3D1%26csrfT%3Dgk0uOPNMvu0vp43TwSGgyrQtSJHyFZ2rpwOp%252B7oAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23R3IMG32674IFV4&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gk0uOPNMvu0vp43TwSGgyrQtSJHyFZ2rpwOp%2B7oAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R3IMG32674IFV4&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=gk0uOPNMvu0vp43TwSGgyrQtSJHyFZ2rpwOp%2B7oAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R3IMG32674IFV4&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-R1X9YMCS5VJJJN"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AEID5LYW5LVQGG7BALNJG23MGKPA/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">Gary Niblock</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/R1X9YMCS5VJJJN/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="5.0 out of 5 stars"><i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/R1X9YMCS5VJJJN/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Perfect for housing my 10’ surfboard and keeping wax off my van and other boards.</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on March 6, 2019</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-color-secondary" data-hook="format-strip-linkless">Size: 10'2 x26" wide</span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  This inexpensive bag is perfect for my needs. I keep as many boards as I can in my van which include SUPs as well as surfboards. I don’t like getting wax all over my van, my boards and the other stuff I keep in the van. Keeping my surfboard in this bag makes it easy and clean. I can’t attest to it’s durability or ability to withstand the weather because it rarely sees the outside of my van. But for my use it is perfect.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">One person found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DR1X9YMCS5VJJJN%26voteValue%3D1%26csrfT%3DghuT5hkPR2lLPqnOapNPX4TA%252F82ePGbkN2SBtaQAAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23R1X9YMCS5VJJJN&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=ghuT5hkPR2lLPqnOapNPX4TA%2F82ePGbkN2SBtaQAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R1X9YMCS5VJJJN&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=ghuT5hkPR2lLPqnOapNPX4TA%2F82ePGbkN2SBtaQAAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=R1X9YMCS5VJJJN&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>, <div class="a-section celwidget" id="customer_review-RZ08P83P7OEQB"><div class="a-row a-spacing-mini" data-hook="genome-widget"><a class="a-profile" data-a-size="small" href="/gp/profile/amzn1.account.AE7GGSTC6A5K5OVIMAWYWPOWE5CA/ref=cm_cr_dp_d_gw_tr?ie=UTF8"><div aria-hidden="true" class="a-profile-avatar-wrapper"><div class="a-profile-avatar"><img class="a-lazy-loaded" data-src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" src="https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/grey-pixel.gif"/><noscript><img src="https://images-na.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png"/></noscript></div></div><div class="a-profile-content"><span class="a-profile-name">bolink</span></div></a></div><div class="a-row"><a class="a-link-normal" href="/gp/customer-reviews/RZ08P83P7OEQB/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI" title="5.0 out of 5 stars"><i class="a-icon a-icon-star a-star-5 review-rating" data-hook="review-star-rating"><span class="a-icon-alt">5.0 out of 5 stars</span></i></a><span class="a-letter-space"></span><a class="a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold" data-hook="review-title" href="/gp/customer-reviews/RZ08P83P7OEQB/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&amp;ASIN=B00KOIM9OI">
<span>Really good buy</span>
</a></div><span class="a-size-base a-color-secondary review-date" data-hook="review-date">Reviewed in the United States on November 20, 2017</span><div class="a-row a-spacing-mini review-data review-format-strip"><span class="a-color-secondary" data-hook="format-strip-linkless">Size: 7'6</span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-size-mini a-color-state a-text-bold" data-hook="avp-badge-linkless">Verified Purchase</span></div><div class="a-row a-spacing-small review-data"><span class="a-size-base review-text" data-hook="review-body"><div aria-live="polite" class="a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container" data-a-expander-collapsed-height="300" data-a-expander-name="review_text_read_more" style="max-height:300px"><div aria-expanded="false" class="a-expander-content reviewText review-text-content a-expander-partial-collapse-content" data-hook="review-collapsed">
<span>
  These bags are light weight and good as a day bag.<br/>This model fits thick and wide boards.<br/>My board is 23.5 wide and 3.75 thick and it fits easily.
</span>
</div><div class="a-expander-header a-expander-partial-collapse-header"><div class="a-expander-content-fade"></div><a aria-label="Toggle full review text" class="a-declarative" data-a-expander-toggle='{"allowLinkDefault":true, "expand_prompt":"Read more", "collapse_prompt":"Read less"}' data-action="a-expander-toggle" data-hook="expand-collapse-read-more-less" href="javascript:void(0)"><i class="a-icon a-icon-extender-expand"></i><span class="a-expander-prompt">Read more</span></a></div></div></span></div><div class="a-row review-comments cr-vote-action-bar" data-hook="review-comments"><span class="cr-vote" data-hook="review-voting-widget">
<div class="a-row a-spacing-small"><span class="a-size-base a-color-tertiary cr-vote-text" data-hook="helpful-vote-statement">8 people found this helpful</span></div><div class="cr-helpful-button aok-float-left">
<span class="a-button a-button-base"><span class="a-button-inner"><a class="a-button-text" data-hook="vote-helpful-button" href="https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB00KOIM9OI%2Fref%3Dcm_cr_dp_d_vote_lft%3Fie%3DUTF8%26voteInstanceId%3DRZ08P83P7OEQB%26voteValue%3D1%26csrfT%3DggQ2oDi%252BZKTD%252B5uWunmYVyTCRKw5AWBY8xUko90AAAABAAAAAGA3C2tyYXcAAAAA%252B4kUEk%252F7iMGR3xPcX6iU%23RZ08P83P7OEQB&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.assoc_handle=usflex&amp;openid.mode=checkid_setup&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0" role="button"><div class="cr-helpful-text">
          Helpful</div>
</a></span></span></div>
</span><span class="cr-footer-line-height">
<span><i aria-label="|" class="a-icon a-icon-text-separator" role="img"></i><span class="a-declarative" data-action="cr-popup" data-cr-popup='{"width":"580","title":"ReportAbuse","url":"/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=ggQ2oDi%2BZKTD%2B5uWunmYVyTCRKw5AWBY8xUko90AAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=RZ08P83P7OEQB&amp;sessionId=132-2185043-0688438","height":"380"}'><a class="a-size-base a-link-normal a-color-secondary report-abuse-link a-text-normal" href="/hz/reviews-render/report-abuse?ie=UTF8&amp;voteDomain=Reviews&amp;ref=cm_cr_dp_d_report&amp;csrfT=ggQ2oDi%2BZKTD%2B5uWunmYVyTCRKw5AWBY8xUko90AAAABAAAAAGA3C2tyYXcAAAAA%2B4kUEk%2F7iMGR3xPcX6iU&amp;entityId=RZ08P83P7OEQB&amp;sessionId=132-2185043-0688438">Report abuse</a></span></span></span>
</div></div>